mod 'puppet-nginx', '4.0.0'
mod 'puppetlabs/concat'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/docker'
mod 'puppetlabs/apt'
mod 'puppetlabs/powershell'
mod 'puppetlabs/pwshlib'
mod 'puppetlabs/reboot'
mod 'samuelson-dockeragent'
mod 'puppetlabs/docker'
